# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: CASIA-B
  dataset_root: /mnt/nas/public_data/gait/CASIA-B-pkl/
  dataset_partition: ./datasets/CASIA-B/CASIA-B.json
  num_workers: 16
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: CASIA-B

evaluator_cfg:
  enable_distributed: true
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 0
  save_name: SPOSGait_small-casiab-supertraining_2loss
  sampler:
    batch_shuffle: false
    batch_size: 1  #1 for search
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  choice_debug: False
  choice_max_num: [1, 6, 6, 6]
  model: SPOSGait_small
  channels: [96, 192, 256]
  class_num: 74
  SeparateFCs:
    in_channels: 256
    out_channels: 256
    parts_num: 16
  SeparateBNNecks:
    class_num: 74
    in_channels: 256
    parts_num: 16
  bin_num:
    - 16

retrain: # 对应SPOSGait_large.py 230行
  search_network: [0, 5, 0, 1]   #  SPOSGait retrain flg!!!
  
optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 40000
    - 60000
    - 80000
  scheduler: MultiStepLR

trainer_cfg:
  enable_distributed: true
  enable_float16: true
  with_test: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: SPOSGait_small-casiab-supertraining_2loss
  sync_BN: true
  total_iter: 100000
  sampler:
    batch_shuffle: true
    batch_size:
      - 32
      - 4
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
